/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/LandingPage/AboutSection.vue')['default']
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AuthLayout: typeof import('./src/components/layout/AuthLayout.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    BgBlock: typeof import('./src/components/ui/bgBlock.vue')['default']
    Button: typeof import('primevue/button')['default']
    ColRegistered: typeof import('./src/components/dashboard/admin/courses/ColRegistered.vue')['default']
    CoursesTable: typeof import('./src/components/dashboard/admin/courses/CoursesTable.vue')['default']
    CourseTable: typeof import('./src/components/dashboard/admin/courses/CourseTable.vue')['default']
    DashboardLayout: typeof import('./src/components/layout/DashboardLayout.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Editor: typeof import('primevue/editor')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Form: typeof import('./src/components/dashboard/admin/courses/Form.vue')['default']
    FormAnswer: typeof import('./src/components/dashboard/admin/courses/FormAnswer.vue')['default']
    FormQuestion: typeof import('./src/components/dashboard/admin/courses/FormQuestion.vue')['default']
    FormSubject: typeof import('./src/components/dashboard/admin/courses/FormSubject.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HeroSection: typeof import('./src/components/LandingPage/HeroSection.vue')['default']
    Image: typeof import('primevue/image')['default']
    ListQuestionView: typeof import('./src/components/dashboard/admin/courses/ListQuestionView.vue')['default']
    ListTutorView: typeof import('./src/components/dashboard/admin/courses/ListTutorView.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    LoginGoogle: typeof import('./src/components/ui/LoginGoogle.vue')['default']
    OtpForm: typeof import('./src/components/auth/OtpForm.vue')['default']
    ProgramTable: typeof import('./src/components/dashboard/admin/programs/ProgramTable.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    RerenderChildren: typeof import('./src/components/ui/RerenderChildren.vue')['default']
    ResendForm: typeof import('./src/components/auth/ResendForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    UploadImage: typeof import('./src/components/ui/UploadImage.vue')['default']
    UserTable: typeof import('./src/components/dashboard/admin/users/UserTable.vue')['default']
  }
}
