/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/LandingPage/AboutSection.vue')['default']
    AuthLayout: typeof import('./src/components/layout/AuthLayout.vue')['default']
    BgBlock: typeof import('./src/components/ui/bgBlock.vue')['default']
    CoursesTable: typeof import('./src/components/dashboard/admin/courses/CoursesTable.vue')['default']
    CourseTable: typeof import('./src/components/dashboard/admin/courses/CourseTable.vue')['default']
    DashboardLayout: typeof import('./src/components/layout/DashboardLayout.vue')['default']
    Editor: typeof import('primevue/editor')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Form: typeof import('./src/components/dashboard/admin/courses/Form.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HeroSection: typeof import('./src/components/LandingPage/HeroSection.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    LoginGoogle: typeof import('./src/components/ui/LoginGoogle.vue')['default']
    OtpForm: typeof import('./src/components/auth/OtpForm.vue')['default']
    ProgramTable: typeof import('./src/components/dashboard/admin/programs/ProgramTable.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    RerenderChildren: typeof import('./src/components/ui/RerenderChildren.vue')['default']
    ResendForm: typeof import('./src/components/auth/ResendForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    UploadImage: typeof import('./src/components/ui/UploadImage.vue')['default']
    UserTable: typeof import('./src/components/dashboard/admin/users/UserTable.vue')['default']
  }
}
