/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/LandingPage/AboutSection.vue')['default']
    AuthLayout: typeof import('./src/components/layout/AuthLayout.vue')['default']
    BgBlock: typeof import('./src/components/ui/bgBlock.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CardCountSubtest: typeof import('./src/components/dashboard/tutor/tryouts/CardCountSubtest.vue')['default']
    CardCourses: typeof import('./src/components/dashboard/tutor/courses/CardCourses.vue')['default']
    CardTryouts: typeof import('./src/components/dashboard/tutor/tryouts/CardTryouts.vue')['default']
    ColRegisteredCourses: typeof import('./src/components/dashboard/admin/courses/ColRegisteredCourses.vue')['default']
    ColRegisteredTryouts: typeof import('./src/components/dashboard/admin/tryouts/ColRegisteredTryouts.vue')['default']
    CourseRegistrationTable: typeof import('./src/components/dashboard/admin/courses/CourseRegistrationTable.vue')['default']
    CourseTable: typeof import('./src/components/dashboard/admin/courses/CourseTable.vue')['default']
    CreateQuestion: typeof import('./src/components/dashboard/tutor/tryouts/CreateQuestion.vue')['default']
    DashboardLayout: typeof import('./src/components/layout/DashboardLayout.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    FormAnswer: typeof import('./src/components/dashboard/admin/courses/FormAnswer.vue')['default']
    FormCourses: typeof import('./src/components/dashboard/admin/courses/FormCourses.vue')['default']
    FormCreateQuestion: typeof import('./src/components/dashboard/tutor/tryouts/FormCreateQuestion.vue')['default']
    FormPrograms: typeof import('./src/components/dashboard/admin/programs/FormPrograms.vue')['default']
    FormQuestion: typeof import('./src/components/dashboard/admin/courses/FormQuestion.vue')['default']
    FormSubject: typeof import('./src/components/dashboard/admin/courses/FormSubject.vue')['default']
    FormTryout: typeof import('./src/components/dashboard/admin/tryouts/FormTryout.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HeroSection: typeof import('./src/components/LandingPage/HeroSection.vue')['default']
    Image: typeof import('primevue/image')['default']
    ListQuestionView: typeof import('./src/components/dashboard/admin/courses/ListQuestionView.vue')['default']
    ListTutorView: typeof import('./src/components/dashboard/admin/courses/ListTutorView.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    OtpForm: typeof import('./src/components/auth/OtpForm.vue')['default']
    ProgramTable: typeof import('./src/components/dashboard/admin/programs/ProgramTable.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    ResendForm: typeof import('./src/components/auth/ResendForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TryoutRegistrationTable: typeof import('./src/components/dashboard/admin/tryouts/TryoutRegistrationTable.vue')['default']
    TryoutTable: typeof import('./src/components/dashboard/admin/tryouts/TryoutTable.vue')['default']
    UploadImage: typeof import('./src/components/ui/UploadImage.vue')['default']
    UserTable: typeof import('./src/components/dashboard/admin/users/UserTable.vue')['default']
  }
}
